/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customerPhone' : IDL.Text,
  'orderStatus' : IDL.Text,
  'shippingStatus' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'platform' : IDL.Text,
  'orderValue' : IDL.Float64,
  'orderId' : IDL.Text,
  'notes' : IDL.Text,
  'createdTimestamp' : Time,
  'quantity' : IDL.Nat,
});
export const ProductTag = IDL.Variant({
  'premium' : IDL.Null,
  'festive' : IDL.Null,
  'bestseller' : IDL.Null,
  'daily' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'unspecified' : IDL.Null,
  'lehenga' : IDL.Null,
  'saree' : IDL.Null,
  'dupatta' : IDL.Null,
  'fabric' : IDL.Null,
  'kurta' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'marketplacePrice' : IDL.Float64,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(ProductTag),
  'sellingPrice' : IDL.Float64,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'reservedStock' : IDL.Nat,
  'createdTimestamp' : Time,
  'category' : ProductCategory,
  'colors' : IDL.Vec(IDL.Text),
  'costPrice' : IDL.Float64,
  'fabric' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrder' : IDL.Func([Order], [IDL.Nat], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customerPhone' : IDL.Text,
    'orderStatus' : IDL.Text,
    'shippingStatus' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'platform' : IDL.Text,
    'orderValue' : IDL.Float64,
    'orderId' : IDL.Text,
    'notes' : IDL.Text,
    'createdTimestamp' : Time,
    'quantity' : IDL.Nat,
  });
  const ProductTag = IDL.Variant({
    'premium' : IDL.Null,
    'festive' : IDL.Null,
    'bestseller' : IDL.Null,
    'daily' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'unspecified' : IDL.Null,
    'lehenga' : IDL.Null,
    'saree' : IDL.Null,
    'dupatta' : IDL.Null,
    'fabric' : IDL.Null,
    'kurta' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'marketplacePrice' : IDL.Float64,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(ProductTag),
    'sellingPrice' : IDL.Float64,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'reservedStock' : IDL.Nat,
    'createdTimestamp' : Time,
    'category' : ProductCategory,
    'colors' : IDL.Vec(IDL.Text),
    'costPrice' : IDL.Float64,
    'fabric' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrder' : IDL.Func([Order], [IDL.Nat], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };