/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'paymentMethod' : string,
  'customerPhone' : string,
  'orderStatus' : string,
  'shippingStatus' : string,
  'productId' : bigint,
  'productName' : string,
  'platform' : string,
  'orderValue' : number,
  'orderId' : string,
  'notes' : string,
  'createdTimestamp' : Time,
  'quantity' : bigint,
}
export interface Product {
  'id' : bigint,
  'sku' : string,
  'marketplacePrice' : number,
  'stockQuantity' : bigint,
  'name' : string,
  'tags' : Array<ProductTag>,
  'sellingPrice' : number,
  'description' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'imageUrl' : [] | [string],
  'reservedStock' : bigint,
  'createdTimestamp' : Time,
  'category' : ProductCategory,
  'colors' : Array<string>,
  'costPrice' : number,
  'fabric' : string,
}
export type ProductCategory = { 'unspecified' : null } |
  { 'lehenga' : null } |
  { 'saree' : null } |
  { 'dupatta' : null } |
  { 'fabric' : null } |
  { 'kurta' : null };
export type ProductTag = { 'premium' : null } |
  { 'festive' : null } |
  { 'bestseller' : null } |
  { 'daily' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrder' : ActorMethod<[Order], bigint>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];